<?php
/*****************************************************************************
 *   Copyright (C) 2006-2009, onPHP's MetaConfiguration Builder.             *
 *   Generated by onPHP-1.1.master at 2012-10-28 12:28:55                    *
 *   This file will never be generated again - feel free to edit.            *
 *****************************************************************************/

namespace Onphp\NsConverter\EntitieProto;

use \Onphp\EntityProto;
use \Onphp\Primitive;

class ConverterEntity extends EntityProto
{
	/**
	 * @return ConverterEntity
	 */
	public static function me()
	{
		return self::getInstance(__CLASS__);
	}

	public function getFormMapping()
	{
		return array(
			'confdir' => Primitive::string('confdir')->required(),
			'pathes' => Primitive::formsList('pathes')->ofProto(PathEntity::me())->required(),
		);
	}
}